= Необходимые ресурсы

[#server]
== Требования серверной части модуля

[cols="34%,66%", options="header"]
|===
|Требование
|Подробности

|[[linux]]Операционная система
a|.Для установки на Linux:
* Astra Linux Special Edition {l-1}.
* Astra Linux Special Edition {l-1-1}.

|[[hard]]Необходимое техническое обеспечение
|Специальные требования к аппаратному обеспечению не предъявляются.

|Необходимое программное обеспечение
|Специальные требования к программному обеспечению не предъявляются.
|===

[#client]
== Требования клиентской части модуля

[cols="34%,66%", options="header"]
|===
|Требование
|Подробности

|Необходимое техническое обеспечение
|Специальные требования к аппаратному обеспечению не предъявляются.

|Операционная система:
a|
// * ОС Windows:
// ** Microsoft Windows {w-client-1}.
// ** Microsoft Windows {w-client-2}.
// ** Microsoft Windows {w-client-3}.
// ** Microsoft Windows {w-client-4}.
* ОС Windows для работы в {wincl}е или любая ОС, перечисленная в требованиях к установке системы, см. "xref:install-linux:ROOT:requirements-software.adoc[]" для работы в {wc}е.

|Для возможности сканирования документов из карточек Приложения требуется сканер с http://ru.wikipedia.org/wiki/TWAIN[TWAIN-совместимым интерфейсом].

|Из-за возможных различий в реализации TWAIN-интерфейса в драйвере устройства не гарантируется корректная работа модуля со всеми моделями сканеров, а также с двусторонними сканерами. В частности, известно о некорректной работе с моделями сканеров "Ricoh Aficio 20xx (MB 92xx, UNIT D335)" и "Fujitsu FI 6130/6140".

.Сканеры, сертифицированные для работы в системе {dv}:
* WIA: Epson Workforce PS-6500.
* TWAIN: Epson GT-S55, Epson P-215.

Рекомендуется проверить совместимость с конкретными сканерами до начала использования продукта. Компания "ДоксВижн" не несет ответственности за некорректную работу сканеров и иного оборудования. Отсутствие совместимости с конкретной моделью сканера, или отличия в поведении сканирования из системы {dv} по сравнению со сканированием в стороннем ПО, не могут являться основанием для рекламации или обращения в техническую поддержку "ДоксВижн".
|===

[#docsvision]
== Требования к системе {dv}

. База данных {dv} должна функционировать под управлением СУБД {mssql} Server. Возможность работы с карточками {to} в системе с БД {pgsql} -- недоступна.
. Для корректной работы данной версии модуля _{bo}_ требуется установить *серверную* и *клиентскую* части следующих модулей:
+
.. Модуль {pl} {pl-req} и выше.
.. Модуль {bo} {bo-req} и выше.
.. Модуль {dm} {dm-req} и выше.
.. Приложение {wf} {wf-req} и выше.
.. Модуль {ad} {ad-req} и выше.
.. Модуль Служба {ws} {ws-req} и выше.
.. Клиентская часть модуля {wincl} {win-req} и выше, если планируется работать в {wincl}е.
. Дополнительное программное обеспечение для работы функции распознавания в карточках приложения:
.. ABBYY FineReader Scripting Edition 6.0/7.0.

[#license]
== Лицензия

. Для работы с приложением _{to}_ лицензия на систему {dv} должна содержать дополнительную опцию: _{dv} Personal Assistant_ (для работы с программой _Личный помощник_).
. Для работы с карточками и справочниками приложения _Делопроизводства 4.5_ отдельная лицензионная опция не требуется.
. Опция _Сервис обслуживания электронной подписи_ необходима для улучшения подписи до архивной (добавление архивного штампа времени). +
При использовании Криптосервиса только для отображения информации в журнале подписей дополнительные лицензии не требуются
