= Уровень подготовки пользователя

Для эксплуатации приложения _{to}_ определены две пользовательские роли: администратор {dv} и конечный пользователь. Настройку _решения_ на базе системы {dv} с использованием Приложения выполняет инженер {dv}.

Администратор {dv} устанавливает Приложение (серверную и клиентскую части), выполняет первоначальную настройку.

Инженер {dv} настраивает работу с карточками Приложения с помощью предоставляемых _справочников_ {dv}, разрабатывает скрипты карточек.

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой и т.п.

Администратор или конечный пользователь {dv} заполняют и актуализируют справочники {dv}.

Все пользователи Приложения должны обладать базовыми навыками работы на персональном компьютере, в программе "{wincl}" (модуль "{wincl}").

Администратор {dv} должен обладать навыками настройки модуля "Платформа", формирования сертификатов ЭЦП в ОС Windows; а также ознакомиться с документом _Приложение _{to}_. Руководство администратора_.

Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}, иметь опыт разработки на языке Visual Basic; должен ознакомиться с данным руководством пользователя и с документом _Приложение _{to}_. Руководство администратора_.

Конечные пользователи должны ознакомиться с руководством пользователя.