= Уровень подготовки пользователя

Для эксплуатации модуля {to} определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации и настройки решений появляются дополнительные роли: инженер и разработчик {dv}.

Администратор {dv} устанавливает модуль, выполняет первоначальную настройку. Администратор (или конечный пользователь {dv}) заполняет и актуализирует справочники {dv}. Администратор {dv} должен обладать навыками настройки модуля "Платформа", формирования сертификатов ЭЦП в ОС Windows; а также ознакомиться с документацией по xref:admin:install.adoc[администрированию модуля] {to}.

Конечный пользователь выполняет работы, связанные с обработкой карточек модуля, он также может заполнять и актуализировать справочники {dv}, выполнять прочие действия. Конечные пользователи должны ознакомиться с xref:user:prepare.adoc[разделом документации] для пользователей. Основным пользовательским рабочим местом является xref:6.1@webclient:user:launch.adoc[{wc}]. Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере и в интернет браузере.

Инженер {dv} настраивает работу с карточками модуля с помощью предоставляемых справочников {dv}, разрабатывает скрипты карточек. Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}, должен ознакомиться с xref:user:prepare.adoc[руководством пользователя] и с документацией xref:admin:install.adoc[по администрированию] модуля.

Разработчик {dv} создаёт скрипты карточек, взаимодейстувует с карточками с использованием API {dv}, может разрабатывать новые функции системы. Разработчик должен обладать навыками C# или Visual Basic .NET, ознакомиться с данной документацией для модуля {to}, а также документацией в разделе xref:programmer::index.adoc[Руководство разработчика {dv}].
