= Уровень подготовки пользователя

Для эксплуатации приложения {dm} определены две пользовательские роли: администратор {dv} и конечный пользователь. На этапе внедрения системы {dv} в организации и настройки решений появляются дополнительные роли: инженер и разработчик {dv}.

Администратор {dv} устанавливает Приложение, выполняет первоначальную настройку. Администратор (или конечный пользователь {dv}) заполняет и актуализирует справочники {dv}. Администратор {dv} должен обладать навыками настройки модуля "Платформа", формирования сертификатов ЭЦП в ОС Windows; а также ознакомиться с документацией по xref:admin:install.adoc[администрированию модуля] "Приложение {to}".

Конечный пользователь выполняет работы, связанные с регистрацией документов в системе {dv}, их обработкой, он также может заполнять и актуализировать справочники {dv} и т.п. Конечные пользователи должны ознакомиться с xref:user:prepare.adoc[разделом документации] для пользователей. Основным пользовательским рабочим местом является xref:dev@webclient:user:launch.adoc[{wc}]. Все пользователи модуля должны обладать базовыми навыками работы на персональном компьютере и в интернет браузере.

Инженер {dv} настраивает работу с карточками Приложения с помощью предоставляемых справочников {dv}, разрабатывает скрипты карточек. Инженер {dv} должен быть знаком с предметной областью и процессами документооборота организации, в которой выполняется внедрение {dv}, должен ознакомиться с xref:user:prepare.adoc[руководством пользователя] и с документацией xref:admin:install.adoc[по администрированию] модуля.

Разработчик {dv} создаёт скрипты карточек, взаимодейстувует с карточками с использованием API {dv}, может разрабатывать новые функции системы. Разработчик должен иметь опыт разработки на языке C# или Visual Basic .NET, ознакомиться с данной документацией для Приложения {to}, а также документацией в разделе xref:programmer::index.adoc[Руководство разработчика {dv}].
