= Автоматическое наложение подписи при согласовании

Для участника согласования может быть настроена возможность автоматического или ручного подписания согласуемых документов. При выборе автоматического режима, подписание производится от имени текущего сотрудника и только при наличии действующего сертификата подписи. Наложение подписи выполняется одновременно на все версии документов (файлов), созданные текущим пользователем и прикрепленные к карточке согласования.

Чтобы настроить подписание карточек делопроизводства, выполните следующие действия:

. В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем в области _Действия_ перейдите по ссылке _Расширенные настройки_, чтобы открыть окно "xref:cards.adoc[Карточки]".
. В секции _Прочее_ для атрибутов, которые требуют автоматического наложения подписи, значения *_True_*.
+
Если установлено значение этого поля *_True_*, то ЭЦП в карточке согласования будет проставляться автоматически при установке признака `Согласован`/`Не согласован`.
