= Права на карточки Делопроизводства 4.5

Права на карточки Делопроизводства 4.5 может быть настроены:

* <<deputies,Для заместителей>>.
* На редактирование полей.

.Чтобы определить права на карточки Делопроизводства, выполните следующие действия:
. В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем в области _Действия_ перейдите по ссылке _Расширенные настройки_, чтобы открыть окно xref:cards.adoc[Карточки].
. В секции _Права_ выберите пользователей, которые смогут редактировать любые поля карточек, включая поля, помеченные в справочнике типов как предназначенные только для чтения.

[#deputies]
== Права для заместителей

Чтобы определить права на карточки Делопроизводства для заместителей:

. Выполните любое из действий:
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем найдите область "xref:cards.adoc[Настройка параметров для заместителей]".
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем в области _Действия_ перейдите по ссылке _Расширенные настройки_ затем найдите в области _Права_ параметр "xref:cards.adoc[Права доступа для заместителей]".
. Настройте для заместителей способ выдачи прав доступа на карточки замещаемого лица. Для этого выберите требуемую опцию или установите значения параметра _Права доступа для заместителей_:
+
* *_Выдавать всем_* -- всем заместителям, указанным в справочнике сотрудников, будут выдаваться права на карточки, аналогичные правам замещаемого.
* *_Не выдавать никому_* -- права на карточки, выданные замещаемому лицу, не будут распространяться на его заместителей.
* *_Назначать индивидуально_* -- можно будет выбрать заместителей, которым будут переданы права на карточки от замещаемого лица. Остальные заместители аналогичных прав не получат.
+
. Чтобы вновь назначаемым заместителям выдавались права на карточки, уже существующие в системе, установите флаг `*Разрешить доступ для новых заместителей*` или установите значение параметра как *_True_*. Права будут выдаваться при назначении сотрудника заместителем.
