= Настройки карточек типа "Документ"

Чтобы настроить параметры карточек типа _Документ_, выполните следующие действия:

. Выполните любое из действий:
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем найдите область xref:cards.adoc[*Настройки карточек документов*];
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем в области *Действия* перейдите по ссылке _Расширенные настройки_ затем найдите область "xref:cards.adoc[Прочие]".
. Чтобы запретить изменение значения поля *Зарегистрировал* (которое автоматически заполняется при создании карточки документа фамилией сотрудника, создавшего карточку) установите флаг *Запретить изменение регистратора в карточках документов* или установите значение параметра *Запретить изменение регистратора* равным `True`.
. Чтобы запретить изменение даты регистрации в карточках любым пользователем, кроме указанных в группе секции *Право редактирования* этого же окна, установите флаг *Запретить изменение даты регистрации в карточках* или значение одноименного параметра равным `True`.
. Чтобы для пользователя, не являющегося администратором, свойства карточек документов отображались только в режиме формы и не были доступны для редактирования, установите флаг *Запретить отображение пользовательских свойств в виде таблицы* или значение одноименного параметра равным `True`.
. <<fullnames,Настройте способ отображения названий организаций-контрагентов>>.

[#fullnames]
== Использование полных названий контрагентов в карточках

В карточках приложения _{to}_ можно настроить предпочтительный способ отображения названий контрагентов. Отображаться могут как полные названия контрагентов, указанные в _Справочнике контрагентов_ в поле _Полное название_, так и сокращенные названия.

Чтобы названия организаций-контрагентов в полях карточек входящих и исходящих документов, указанные в поле _Полное название справочника контрагентов_, отображались полностью, установите флаг `*Использовать полные названия контрагентов в карточках*`. При снятом флаге будут отображаться сокращенные названия.

.Чтобы настроить способ отображения названий контрагентов в карточках, выполните следующие действия:
. Выполните любое из действий:
+
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем найдите область "xref:cards.adoc[Настройки карточек документов]".
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем в области *Действия* перейдите по ссылке _Расширенные настройки_ затем найдите область "xref:cards.adoc[Прочие]".
+
. Чтобы названия организаций-контрагентов отображались полностью, установите флаг `*Использовать полные названия контрагентов в карточках*` или установите значение параметра *_True_*.
+
При снятом флаге или значении параметра *_False_* будут отображаться сокращенные названия.
