= Настройки карточек типа "Файл"

.Чтобы настроить параметры карточек типа _Файл_:
. Выполните любое из действий:
+
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем найдите область "xref:cards.adoc[Настройки карточек файлов]".
* В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем в области _Действия_ перейдите по ссылке _Расширенные настройки_, затем найдите область "xref:cards.adoc[Прочие]".
+
. Определите способ открытия карточки файла, созданной по шаблону, в момент создания:
+
* Чтобы карточка открывалась как карточка {dv}, установите флаг `*Карточку файла, созданную по шаблону, открывать как карточку*` или установите значение параметра _Карточку файла открывать как карточку_ равное *_True_*.
* Чтобы карточка открывалась как файл Word, Paint или другого внешнего приложения, снимите флаг или установите значение параметра *_False_*.
+
. Чтобы все версии файла (если для него установлен автоматический способ создания версий), хранящиеся в шаблоне карточки файла, были скопированы в создаваемую карточку, установите флаг `*Сохранять все версии файла в карточке файла, созданной по шаблону*` или установите значение параметра _Сохранять все версии файла_ равным *_True_*.
