= Использование полных названий контрагентов в карточках

В карточках Делопроизводства 4.5 можно настроить предпочтительный способ отображения названий контрагентов. Отображаться могут как полные названия контрагентов, указанные в _Справочнике контрагентов_ в поле *Полное название*, так и сокращенные названия.

Чтобы настроить способ отображения названий контрагентов в карточках, выполните следующие действия:

названия организаций-контрагентов в полях карточек входящих и исходящих документов, указанные в поле Полное название справочника контрагентов, отображались полностью, установите флаг *Использовать полные названия контрагентов в карточках*. При снятом флаге будут отображаться сокращенные названия.

. Выполните любое из действий:
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем найдите область xref:OfficeWork_Cards.html#task_xsm_lpn_34__OfficeWorksCards[*Настройки карточек документов*];
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем в области *Действия* перейдите по ссылке *Расширенные настройки*, затем найдите область xref:OfficeWork_Cards.html#task_xsm_lpn_34__OfficeWorkCards_extra[*Прочие*].
. Чтобы названия организаций-контрагентов отображались полностью, установите флаг *Использовать полные названия контрагентов в карточках* или установите значение параметра [.kbd .ph .userinput]`True`.
+
При снятом флаге или значении параметра [.kbd .ph .userinput]`False` будут отображаться сокращенные названия.
