= Проверка уникальности реквизитов секции 'Содержание'

Для карточек Делопроизводства может быть настроена проверка совпадения данных документа, присланного контрагентом, с данными уже имеющихся в системе карточек входящих документов.

Проверка производится при сохранении или закрытии карточки входящего документа, создаваемого по пришедшему исходящему, и, в зависимости от установленных в секции значений полей (_True_ или _False_), может выявить совпадения по:

* *Исходящему номеру*;
* *Дате исходящего* документа;
* *Организации* контрагента, приславшей исходящий документ;
* *Подразделению* контрагента, приславшему исходящий документ.    

Чтобы настроить проверку уникальности реквизитов, выполните следующие действия:

. В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем в области *Действия* перейдите по ссылке *Расширенные настройки*.
+
Будет открыто окно xref:OfficeWork_Cards.html#task_xsm_lpn_34__OfficeWorkCards_extra[*Карточки*].
. В секции *При регистрации входящего документа проверять уникальность реквизитов секции Содержание* для атрибутов, которые требуют проверки уникальности, значение [.keyword .parmname]_True_.
+
Если в секции установлено более одного значения _True_, проверка совпадения данных будет проводиться по их совокупности. Совпадение данных регистрируемой карточки с данными уже имеющихся в системе карточек не является препятствием для регистрации.

Если в создаваемом из входящего исходящем документе номер вводится вручную, то проверка по номеру проводиться не будет, даже если для нее установлено значение _True_.
+
При выявлении совпадений на экран пользователя будет выводится окно со списком найденных карточек. Открыть какую-либо из них можно, дважды щелкнув левой кнопкой мыши по нужной строке списка.
