= Права для заместителей

Чтобы определить права на карточки Делопроизводства для заместителей, выполните следующие действия:

. Выполните любое из действий:
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем найдите область xref:OfficeWork_Cards.adoc[*Настройка параметров для заместителей*];
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем в области *Действия* перейдите по ссылке *Расширенные настройки*, затем найдите в области *Права* параметр xref:OfficeWork_Cards.adoc[*Права доступа для заместителей*].
. Настройте для заместителей способ выдачи прав доступа на карточки замещаемого лица (выберите требуемую опцию или установите значения параметра *Права доступа для заместителей*):
* *Выдавать всем*  — всем заместителям, указанным в справочнике сотрудников, будут выдаваться права на карточки, аналогичные правам замещаемого;
* *Не выдавать никому* — права на карточки, выданные замещаемому лицу, не будут распространяться на его заместителей;
* *Назначать индивидуально* — можно будет выбрать заместителей, которым будут переданы права на карточки от замещаемого лица; остальные заместители аналогичных прав не получат;
. Чтобы вновь назначаемым заместителям выдавались права на карточки, уже существующие в системе, установите флаг *Разрешить доступ для новых заместителей* или установите значение параметра как [.kbd .ph .userinput]`True`. Права будут выдаваться при назначении сотрудника заместителем.
