= Настройки карточек типа 'Файл'

Чтобы настроить параметры карточек типа Файл, выполните следующие действия:

. Выполните любое из действий:
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем найдите область xref:OfficeWork_Cards.adoc[*Настройки карточек файлов*];
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем в области *Действия* перейдите по ссылке *Расширенные настройки*, затем найдите область xref:OfficeWork_Cards.adoc[*Прочие*].
. Определите способ открытия карточки файла, созданной по шаблону, в момент создания:
* чтобы карточка открывалась как карточка {dv}, установите флаг *Карточку файла, созданную по шаблону, открывать как карточку* или установите значение параметра *Карточку файла открывать как карточку* равное [.kbd .ph .userinput]`True`;
* чтобы карточка открывалась как файл Word, Paint или другого внешнего приложения, снимите флаг или установите значение параметра [.kbd .ph .userinput]`False`.
. Чтобы все версии файла (если для него установлен автоматический способ создания версий), хранящиеся в шаблоне карточки файла, были скопированы в создаваемую карточку, установите флаг *Сохранять все версии файла в карточке файла, созданной по шаблону* или установите значение параметра *Сохранять все версии файла* равным [.kbd .ph .userinput]`True`.
