= Автоматическое наложение подписи при согласовании

Для участника согласования может быть настроена возможность автоматического или ручного подписания согласуемых документов. При выборе автоматического режима, подписание производится от имени текущего сотрудника и только при наличии действующего сертификата подписи. Наложение подписи выполняется одновременно на все версии документов (файлов), созданные текущим пользователем и прикрепленные к карточке согласования.

Чтобы настроить подписание карточек делопроизводства, выполните следующие действия:

. В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем в области *Действия* перейдите по ссылке *Расширенные настройки*.
+
Будет открыто окно xref:OfficeWork_Cards.adoc[*Карточки*].
. В секции *Прочее* для атрибутов, которые требуют автоматического наложения подписи, значения [.keyword .parmname]_True_.
+
Если установлено значение этого поля _True_, то ЭЦП в карточке согласования будет проставляться автоматически при установке признака _Согласован_/_Не согласован_.
