= Открытие файлов

Чтобы настроить способ открытия файлов, выполните следующие действия:

. Выполните любое из действий:
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем найдите область xref:OfficeWork_Cards.html#task_xsm_lpn_34__OfficeWorksCards[*Настройки открытия файлов*];
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем в области *Действия* перейдите по ссылке *Расширенные настройки*, затем найдите область xref:OfficeWork_Cards.html#task_xsm_lpn_34__OfficeWorkCards_extra[*Открытие файлов*].
. Чтобы при открытии файла на чтение пользователю не выдавалось окно с соответствующим предупреждением, установите флаг *Не показывать предупреждение об открытии файла на чтение* или установите значение параметра [.kbd .ph .userinput]`False`.
. Чтобы при открытии файла появлялось окно с вариантами открытия файла (для чтения или для редактирования), установите флаг *Предлагать выбор варианта открытия файла* или установите значение параметра [.kbd .ph .userinput]`True`.
