= Настройки карточек типа 'Документ'

Чтобы настроить параметры карточек типа _Документ_, выполните следующие действия:

. Выполните любое из действий:
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем найдите область xref:OfficeWork_Cards.adoc[*Настройки карточек документов*];
* В области *Категории* выберите ветку *Делопроизводство* > *Карточки*#, затем в области *Действия* перейдите по ссылке *Расширенные настройки*, затем найдите область xref:OfficeWork_Cards.adoc[*Прочие*].
. Чтобы запретить изменение значения поля *Зарегистрировал* (которое автоматически заполняется при создании карточки документа фамилией сотрудника, создавшего карточку) установите флаг *Запретить изменение регистратора в карточках документов* или установите значение параметра *Запретить изменение регистратора* равным [.kbd .ph .userinput]`True`.
. Чтобы запретить изменение даты регистрации в карточках любым пользователем, кроме указанных в группе секции *Право редактирования* этого же окна, установите флаг *Запретить изменение даты регистрации в карточках* или значение одноименного параметра равным [.kbd .ph .userinput]`True`.
. Чтобы для пользователя, не являющегося администратором, свойства карточек документов отображались только в режиме формы и не были доступны для редактирования, установите флаг *Запретить отображение пользовательских свойств в виде таблицы* или значение одноименного параметра равным [.kbd .ph .userinput]`True`.
. xref:OfficeWork_Cards_contragent_fullname.adoc[Настройте способ отображения названий организаций-контрагентов].

