= Назначение и функции Приложения

"{dv} 5. Делопроизводство 4.5" является _базовым модулем_ системы "{dv} 5.5", предназначенным для автоматизации наиболее распространенных задач документооборота.

[NOTE]
====
Приложение является устаревшим, оно обеспечивает совместимость с системой "{dv} 4.5" и рекомендуется к использованию только в организациях, уже использующих Решение, построенное на базе предыдущей версии системы {dv}.
====

Приложение предоставляет следующие возможности:

* создание карточек документов (различных видов) и задач;
* настройка типов карточек "Делопроизводство 4.5"; настройка справочников с записями для использования в карточках;
* настройка бизнес-сценариев на языке Visual Basic для реализации бизнес-логики карточки.

Частью Приложения является программа "Личный помощник", которая позволяет выполнять поиск карточек без использования стандартных средств поиска {dv} и клиентских программ (Windows-клиент, РМА), а также оповещать о появлении новых карточек, соответствующих поисковому запросам.
