= Необходимое техническое обеспечение

== Требования серверной части Приложения

Специальные требования к аппаратному обеспечению не предъявляются.

== Требования клиентской части Приложения

Для возможности сканирования документов из карточек Приложения требуется сканер с http://ru.wikipedia.org/wiki/TWAIN[TWAIN-совместимым интерфейсом].

[NOTE]
====
[.note__title]#Важное замечание: Из-за возможных различий в реализации TWAIN-интерфейса в драйвере устройства не гарантируется совместимость (корректная работа) Модуля со всеми моделями сканеров, а также с двусторонними сканерами. В частности, известно о некорректной работе с моделями сканеров Ricoh Aficio 20xx (MB 92xx, UNIT D335) и Fujitsu FI 6130/6140.

Рекомендуется проверить совместимость с конкретными сканерами до начала использования продукта. Компания "ДоксВижн" не несет ответственности за некорректную работу сканеров и иного оборудования. Отсутствие совместимости с конкретной моделью сканера, или отличия в поведении сканирования из системы {dv} по сравнению со сканированием в стороннем ПО, не могут являться основанием для рекламации или обращения в техническую поддержку ДоксВижн.
====
