= Программное обеспечение, необходимое для использования квалифицированной ЭП

== Требования к серверу

. Компоненты криптопровайдера "КриптоПро":
* КриптоПро CSP версии 3.9/4.0;
* КриптоПро TSPCOM версии 1.05.1379 / 1.05.1057 / 2.0.12450;
* КриптоПро OCSPCOM версии 1.05.1178 / 1.05.1053 / 2.0.12261.
. Сертификаты:
* корневой сертификат КриптоПро – должен быть установлен в хранилище "Доверенные корневые центры сертификации" на уровне "Локальный компьютер".

== Требования к клиентским рабочим местам

. Компоненты криптопровайдера "КриптоПро":
* КриптоПро CSP версии 3.9/4.0;
* КриптоПро TSPCOM версии 1.05.1379 / 1.05.1057 / 2.0.12450;
* КриптоПро OCSPCOM версии 1.05.1178 / 1.05.1053 / 2.0.12261;
* КриптоПро CADESCOM 2.0.13292.
. Сертификаты:
* корневой сертификат удостоверяющего центра, выпустившего сертификат пользовател _*fn:* Например, корневой сертификат КриптоПро._ – должен быть установлен в хранилище "Доверенные корневые центры сертификации" на уровне "Локальный компьютер";
* сертификат пользователя – должен быть установлен в хранилище "Личное" на уровне "Текущий пользователь".

*Обратите внимание*:

* Для формирования и проверки https://www.cryptopro.ru/products/cades/usage#for_what[усовершенствованной ЭП] должны быть установлены все перечисленные компоненты КриптоПро.
* Для использования ключей ЭП ГОСТ Р 34.10-2012 требуется "КриптоПро CSP" версии 4.0.
* По вопросам получения компонентов криптопровайдера "КриптоПро" следует обращаться в компанию ООО "КРИПТО-ПРО".
