= Необходимое программное обеспечение

== Требования серверной части Модуля

. *Модули {dv}*:
[loweralpha]
.. Серверная часть модуля "{dv} 5. Платформа" версии 5.5.2 сборка 4553 и выше.
.. Серверная часть модуля "{dv} 5. Базовые объекты" версии 5.5.3 сборка 5367 и выше.
.. Серверная часть приложения "{dv} 5. Управление документами" версии 5.5.3 сборка 5316 и выше.
.. Серверная часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Серверная часть модуля "{dv} 5. Конструктор согласований" версии 5.5.2 сборка 4221 и выше.
.. Серверная часть модуля "{dv} 5. Windows-клиент" версии 5.5.2 сборка 4248 и выше.

== Требования клиентской части Приложения

. *Модули {dv}*:
[loweralpha]
.. Клиентская часть модуля "{dv} 5. Платформа" версии 5.5.2 сборка 4553 и выше.
.. Клиентская часть модуля "{dv} 5. Базовые объекты" версии 5.5.3 сборка 5367 и выше.
.. Клиентская часть приложения "{dv} 5. Управление документами" версии 5.5.3 сборка 5316 и выше.
.. Клиентская часть модуля "{dv} 5. Управление процессами" версии 5.5.2 сборка 4224 и выше.
.. Клиентская часть модуля "{dv} 5. Конструктор согласований" версии 5.5.2 сборка 4221 и выше.
.. [#concept_vgh_3qm_2db__require]#Клиентская часть модуля "{dv} 5. Windows-клиент" версии 5.5.2 сборка 4248 и выше.
. *Дополнительное программное обеспечение*:
[loweralpha]
.. ABBYY FineReader Scripting Edition 6.0/7.0 – для работы функции распознавания в карточках Приложения.

