= Проверка уникальности реквизитов секции "Содержание"

Для карточек Делопроизводства может быть настроена проверка совпадения данных документа, присланного контрагентом, с данными уже имеющихся в системе карточек входящих документов.

Проверка производится при сохранении или закрытии карточки входящего документа, создаваемого по пришедшему исходящему, и, в зависимости от установленных в секции значений полей (*_True_* или *_False_*), может выявить совпадения по:

* _Исходящему номеру_.
* _Дате исходящего_ документа.
* _Организации_ контрагента, приславшей исходящий документ.
* _Подразделению_ контрагента, приславшему исходящий документ.

Чтобы настроить проверку уникальности реквизитов, выполните следующие действия:

. В области _Категории_ выберите ветку menu:Делопроизводство[Карточки], затем в области _Действия_ перейдите по ссылке _Расширенные настройки_.
+
Будет открыто окно "xref:cards.adoc[Карточки]".
+
. В секции _При регистрации входящего документа проверять уникальность реквизитов секции Содержание_ для атрибутов, которые требуют проверки уникальности, значение *_True_*.
+
NOTE: Если в секции установлено более одного значения *_True_*, проверка совпадения данных будет проводиться по их совокупности. Совпадение данных регистрируемой карточки с данными уже имеющихся в системе карточек не является препятствием для регистрации.
+
Если в создаваемом из входящего исходящем документе номер вводится вручную, то проверка по номеру проводиться не будет, даже если для нее установлено значение *_True_*.
+
При выявлении совпадений на экран пользователя будет выводиться окно со списком найденных карточек. Открыть какую-либо из них можно, дважды щелкнув левой кнопкой мыши по нужной строке списка.
